# Generated by Django 3.1.5 on 2021-01-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210121_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
