# Generated by Django 3.1.5 on 2021-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210126_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
